"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/

NOTA: Este archivo mantiene compatibilidad hacia atrás.
Para desarrollo local multi-tenant, usar project.settings.local
"""

# Redirigir a settings.local si está disponible (para desarrollo local)
import os
environment = os.environ.get('ENVIRONMENT', '').lower()

if environment == 'local' or (not environment and os.environ.get('DJANGO_SETTINGS_MODULE', '').endswith('.local')):
    try:
        from .settings.local import *
    except ImportError:
        # Si no existe settings.local, continuar con configuración antigua
        pass
elif environment == 'production':
    try:
        from .settings.production import *
    except ImportError:
        pass
elif environment in ['qa', 'staging']:
    try:
        from .settings.qa import *
    except ImportError:
        pass

# Si no se importó nada, continuar con configuración antigua
try:
    from corsheaders.defaults import default_headers
except ImportError:
    pass

from pathlib import Path
import logging 

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-zf^1c+5%cj8m5k%^1(5c06e79xo81tgsapvcp1y6n7o74_q_$#')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

# Parse ALLOWED_HOSTS from environment variable or use defaults
allowed_hosts_env = os.environ.get(
    'ALLOWED_HOSTS',
    'chalan-frontend.onrender.com,chalan-backend.onrender.com,localhost,127.0.0.1,192.168.0.248'
)
ALLOWED_HOSTS = [host.strip() for host in allowed_hosts_env.split(',')]

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Application definition

INSTALLED_APPS = [
    'daphne',
    'channels',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'django_filters',
    # 'rest_framework_expiring_authtoken',
    'corsheaders',
    'auditapp',
    'ctrctsapp',
    'crewsapp',
    'appschedule',
    'project',
    'appinventory',
    'apptransactions',
    'appcore',

]

#ASGI_APPLICATION = 'project.asgi.application'

#CHANNEL_LAYERS = {
#    "default": {
#        "BACKEND": "channels.layers.InMemoryChannelLayer",  # Use Redis for production
#    },
#}

MIDDLEWARE = [
    'project.DisableCSRF.DisableCSRF',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Debe ir después de SecurityMiddleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Si usas sesiones de autenticación (en lugar de TokenAuthentication), habilita CSRF
# CSRF Trusted Origins
csrf_origins_env = os.environ.get('CSRF_TRUSTED_ORIGINS', 'http://localhost:8080,http://192.168.0.248:8080,http://192.168.0.248:3000')
CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in csrf_origins_env.split(',')]


# Permitir todas las solicitudes desde el frontend
# En producción, usa CORS_ALLOWED_ORIGINS en lugar de CORS_ALLOW_ALL_ORIGINS
CORS_ALLOW_ALL_ORIGINS = os.environ.get('CORS_ALLOW_ALL_ORIGINS', 'True') == 'True'  # Solo para desarrollo

# CORS_ALLOWED_ORIGINS = [
#     "http://192.168.0.248:3000",
#     "http://localhost:3000",
#     "http://127.0.0.1:3000",
#     "http://192.168.0.248:3000",
#     "ws://192.168.0.248:3000",
#     "ws://localhost:3000",
#     "ws://127.0.0.1:3000",
# ]

CORS_ALLOW_CREDENTIALS = True

# Importar default_headers

#CORS_ALLOWED_ORIGINS = [
#    'https://example.com',
#    'https://sub.example.com',
#    'http://localhost:8080',
#    'http://127.0.0.1:8080',
#    'http://192.168.0.248:8080',
#    'http://localhost:8080',
#    'http://localhost:8000',
#]

CORS_ALLOW_WEBSOCKETS = True

# Permite todos los encabezados CORS estándar
CORS_ALLOW_HEADERS = list(default_headers) + [
    'access-control-allow-origin',
    'X-Custom-Header',
    'X-Requested-With',
    'Authorization',
    'Content-Type'
]

CORS_ALLOW_METHODS = (
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
)

REST_FRAMEWORK = {
    # Definir las clases de autenticación por defecto
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',  # Autenticación con tokens
    ],
    
    # Clases de permisos por defecto (esto afecta las vistas por defecto de DRF)
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',  # Requiere autenticación en todas las vistas
    ],
    
    # Otras configuraciones útiles para DRF
     "EXCEPTION_HANDLER": "project.api.exception_handler.custom_exception_handler",

}

# Asegurarse de que se está utilizando el modelo de usuarios predeterminado de Django
AUTH_USER_MODEL = 'auth.User'

# Usar el backend de permisos de Django
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',  # Backend de autenticación estándar de Django
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'appinventory', 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'
ASGI_APPLICATION = "project.asgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': BASE_DIR / 'db.sqlite3',
#    }
#}

# Database configuration - Supports PostgreSQL (Render) and MySQL
import dj_database_url

# First, try to use DATABASE_URL from environment (Render PostgreSQL)
DATABASE_URL = os.environ.get('DATABASE_URL')

if DATABASE_URL:
    # Use PostgreSQL with Render's DATABASE_URL
    DATABASES = {
        'default': dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    # Fallback to MySQL (local development)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': os.environ.get('MYSQL_DATABASE', 'chalan_sch_txn'),
            'USER': os.environ.get('MYSQL_USER', 'oliver'),
            'PASSWORD': os.environ.get('MYSQL_PASSWORD', '13694344Om$'),
            'HOST': os.environ.get('MYSQL_HOST', 'localhost'),
            'PORT': os.environ.get('MYSQL_PORT', 3306),
            'OPTIONS': {
                'charset': 'utf8mb4',
            },
        }
    }

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# STATIC_ROOT es donde Django recopilará todos los archivos estáticos para producción
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Configuración de WhiteNoise para servir archivos estáticos en producción
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

X_FRAME_OPTIONS = 'SAMEORIGIN' 

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

logger = logging.getLogger('django.db.backends')
logger.setLevel(logging.DEBUG)
logger.addHandler(logging.StreamHandler())

# Configuración para el envío de correos electrónicos
# Configuración para el envío de correos electrónicos con SendGrid
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.sendgrid.net')
EMAIL_PORT = os.environ.get('EMAIL_PORT', 587)  # Usa 465 si prefieres conexión SSL, en cuyo caso ajusta EMAIL_USE_SSL en True y elimina EMAIL_USE_TLS
EMAIL_USE_TLS = True  # Si usas el puerto 587
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', 'apikey')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('EMAIL_DEFAULT_FROM', 'oliver@division16llc.com')

FRONT_URL = os.environ.get('FRONT_URL', 'http://192.168.0.248:8080')

# Channel Layers - Redis configuration
REDIS_URL = os.environ.get('REDIS_URL')

if REDIS_URL:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [REDIS_URL],
            },
        },
    }
else:
    # Fallback to in-memory for development
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer",
        },
    }

ENABLE_WEBSOCKET_NOTIFICATIONS = os.environ.get('ENABLE_WEBSOCKET_NOTIFICATIONS', 'True') == 'True'

LOG_DIR = os.path.join(BASE_DIR, "logs")
os.makedirs(LOG_DIR, exist_ok=True)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {"format": "%(asctime)s [%(levelname)s] %(name)s: %(message)s"}
    },
    "handlers": {
        "console": {"class": "logging.StreamHandler", "formatter": "verbose"},
        "app_file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": os.path.join(LOG_DIR, "app.log"),
            "maxBytes": 10_000_000,
            "backupCount": 5,
            "formatter": "verbose",
        },
    },
    "loggers": {
        "django.request": {"handlers": ["console", "app_file"], "level": "INFO", "propagate": True},
        "appschedule":    {"handlers": ["console", "app_file"], "level": "INFO", "propagate": False},
    },
}
