# Generated by Django 5.0.3 on 2025-10-18 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManualCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Categoría')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
            ],
            options={
                'verbose_name': 'Categoría de Manual',
                'verbose_name_plural': 'Categorías de Manual',
            },
        ),
        migrations.CreateModel(
            name='ManualEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('module', models.CharField(help_text='Ej: Inventario, ERP, Contratos', max_length=100)),
                ('summary', models.TextField(blank=True, help_text='Resumen corto para vista previa o meta descripción.')),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manuals', to='appcore.manualcategory', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Manual Entry',
                'verbose_name_plural': 'Manual Entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
