# Generated by Django 4.2.26 on 2025-11-22 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appcore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Cliente')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, verbose_name='Schema Name')),
                ('tenant_id', models.CharField(max_length=100, unique=True, verbose_name='Tenant ID')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Correo Electrónico')),
                ('client_type', models.CharField(choices=[('electric', 'Electric'), ('air_conditioning', 'Air Conditioning'), ('solar', 'Solar'), ('plumbing', 'Plumbing'), ('hvac', 'HVAC'), ('general', 'General')], default='general', max_length=50, verbose_name='Tipo de Cliente')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='tenant_logos/', verbose_name='Logo del Cliente')),
                ('paid_until', models.DateField(blank=True, null=True, verbose_name='Pagado hasta')),
                ('on_trial', models.BooleanField(default=True, verbose_name='En período de prueba')),
                ('created_on', models.DateField(auto_now_add=True, verbose_name='Creado el')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='appcore.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
